name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Install pods
        run: |
          cd ios
          pod install

      - name: Build iOS
        run: |
          cd ios
          xcodebuild \
            -workspace jellyfin-audio-player.xcworkspace \
            -scheme jellyfin-audio-player \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/App.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        run: |
          cd ios/build
          mkdir Payload
          cp -r App.xcarchive/Products/Applications/*.app Payload/
          zip -r Fintunes.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Fintunes
          path: ios/build/Fintunes.ipa
